# Generated by Django 4.0 on 2021-12-25 22:59

from email.policy import default
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80)),
                ('segmento', models.CharField(max_length=80)),
                ('producto', models.CharField(max_length=80)),
                ('nombreArticulo', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=80)),
                ('descripcionAll', models.CharField(max_length=80)),
                ('fechaRecibido', models.CharField(max_length=80)),
                ('NombreArchivoPDF', models.CharField(max_length=80)),
                ('fotoNombreImagen', models.CharField(max_length=80)),
                ('fechaPublicacion', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('autor', models.CharField(max_length=80)),
                ('enlace', models.CharField(max_length=80)),
                ('sabiasQue', models.CharField(max_length=80)),
                ('objetivoGeneral', models.CharField(max_length=80)),
                ('objetivoEspecifico', models.CharField(max_length=80)),
                ('tipoEstudio', models.CharField(max_length=80)),
                ('metodologia', models.CharField(max_length=80)),
                ('tamañoMuestra', models.CharField(max_length=80)),
                ('ciudades', models.CharField(max_length=80)),
                ('fechaCampo', models.CharField(max_length=80)),
                ('conclusiones', models.CharField(max_length=80)),
                ('agencia', models.CharField(max_length=80)),
                ('accionesLogros', models.CharField(max_length=80)),
                ('valorUnitario', models.CharField(max_length=80)),
                ('catalogacion', models.CharField(max_length=80)),
                ('catalog_process', models.CharField(
                    max_length=80)),
            ],
        ),
    ]
