# Generated by Django 3.2.10 on 2022-01-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211227_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='NombreArchivoPDF',
        ),
        migrations.RemoveField(
            model_name='article',
            name='accionesLogros',
        ),
        migrations.RemoveField(
            model_name='article',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='article',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ciudades',
        ),
        migrations.RemoveField(
            model_name='article',
            name='conclusiones',
        ),
        migrations.RemoveField(
            model_name='article',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='article',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fechaCampo',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fechaRecibido',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fotoNombreImagen',
        ),
        migrations.RemoveField(
            model_name='article',
            name='metodologia',
        ),
        migrations.RemoveField(
            model_name='article',
            name='objetivoEspecifico',
        ),
        migrations.RemoveField(
            model_name='article',
            name='objetivoGeneral',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sabiasQue',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tamañoMuestra',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tipoEstudio',
        ),
        migrations.RemoveField(
            model_name='article',
            name='valorTotal',
        ),
        migrations.RemoveField(
            model_name='article',
            name='valorUnitario',
        ),
        migrations.AlterField(
            model_name='article',
            name='descripcionAll',
            field=models.CharField(max_length=550),
        ),
    ]
