# Generated by Django 3.2.10 on 2022-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='objetivoGeneral',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='catalogacion',
            field=models.CharField(max_length=550),
        ),
    ]
