# Generated by Django 3.2.10 on 2022-01-26 14:28

from email.policy import default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220119_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catalog_process',
            field=models.CharField(default='catalogacion', max_length=550),
            preserve_default=False,
        ),
    ]
