# Generated by Django 3.2.10 on 2022-01-26 14:49

from email.policy import default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_catalog_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='catalog_process',
            field=models.CharField(default=models.CharField(
                max_length=550), max_length=550),
        ),
    ]
