# Generated by Django 3.2.10 on 2022-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_article_catalog_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='catalog_process',
            field=models.CharField(max_length=550),
        ),
    ]
