# Generated by Django 3.2.10 on 2022-02-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_article_catalog_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='synonyms',
            field=models.CharField(default=0, max_length=550),
            preserve_default=False,
        ),
    ]
