# Generated by Django 3.2.10 on 2022-02-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titleProcess',
            field=models.CharField(default=0, max_length=550),
            preserve_default=False,
        ),
    ]
