# Generated by Django 3.2.10 on 2022-02-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_titleprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
