# Generated by Django 3.2.10 on 2022-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220216_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='catalogacion',
            field=models.CharField(max_length=550, verbose_name='Catalogación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='nombreArticulo',
            field=models.CharField(max_length=350, verbose_name='Nombre del estudio'),
        ),
    ]
