# Generated by Django 3.2.10 on 2022-05-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220516_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='FechaPedido',
            field=models.CharField(max_length=550, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='NoLineas',
            field=models.CharField(max_length=350, verbose_name='No de lineas'),
        ),
    ]
